### ISSUE TITLE
`__declspec(dllexport deprecated)` question - difference from R3.x to R4

### ISSUE THREAD

**Issue by slodge** [r-windows/r-base#21]
Hi

I'm looking into a compilation problem for the [cplexAPI](https://cran.r-project.org/web/packages/cplexAPI/) package at the moment.

This package compiles fine on Win10 with R3.6.3 using RTools35.

However with R4.0.3 and RTools40 there are compilation errors caused by the use of `__declspec(dllexport deprecated)` pre-processor injected attributes.

I'm not the first to stumble on this issue. e.g. there are some questions about this problem on:

- https://stackoverflow.com/questions/64762431/installing-cplexapi-with-newest-version-of-cplex-12-10-0-new-error
- https://stackoverflow.com/questions/64033703/cplexapi-installation-compilation-failed
- https://stackoverflow.com/questions/65024457/cplexapi-1-4-0-installiation-on-r4-0-3
- https://stackoverflow.com/questions/63942596/install-rcplex-on-windows

I realise that the changes between the R3 and R4 Windows tool chains are "fairly big", but while trying to migrate this package from R3 to R4, I'm wondering what should be done with these `__declspec(dllexport deprecated)` Microsoft specific attributes? Is this something we need to get modifed within the source headers? Or are there some flags we can set to get the new toolchain to accept them.

Thanks for any pointers here - I used to code in C++ on Microsoft a lot... but I'm fairly rusty now...

Stuart

I'm not a maintainer of the CPlexApi package (I think the api might be IBM internal), but I'm hoping I can help lubricate a fix there...

Also sorry that I can't include much additional information here - but the headers that contain the problem contain a fairly restrictive "Licensed Materials - Property of IBM" warning a the top :/

Finally, there's also a chance here I've somehow messed up my environment and built obj files have somehow been picked up and cached between builds... I've definitely not done much C++ for the last 10 years, and I'm still working out how the R and RTools build chains work...

**Comment by jeroen** [comment]
This seems to be a bug in the cplex library. See also: https://stackoverflow.com/a/61199818/318752

A workaround is to add `-DBUILD_CPXSTATIC` to the `PKG_CPPFLAGS` inside the package `src/Makevars.win` as shown here: https://github.com/r-windows/Rcplex/commit/545254ab7cf28e97e62063c16af711ff2b46476d. 

I also had to update the dll name because the cplex dll is called `cplex12100.dll` while the R package was still assuming `cplex1263`. With these fixes I am able to install the package on Windows:

```r
remotes::install_github("r-windows/rcplex")
```

**Comment by slodge** [comment]
Thanks @jeroen for the feedback and info.

I'm closing this here and am reaching out to the package author.... will hopefully get somewhere with them (and will be able to give them your Stackoverflow comment and the CRAN fork above). I guess the static route just leads to larger image sizes - but that's generally not an issue for any of our users - so should be good 👍 

Thanks 👍  - really appreciated!
